# Generated by Django 5.1.3 on 2024-12-05 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('tipo_servicio', models.TextField(verbose_name='Tipo de Servicio')),
                ('especificaciones', models.TextField(verbose_name='Especificaciones')),
                ('imagen_servicio', models.ImageField(blank=True, null=True, upload_to='image/servicios/', verbose_name='Imagen del Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionAdicionalUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefonico', models.CharField(max_length=15, verbose_name='Número Telefónico')),
                ('direccion_residencia', models.CharField(max_length=255, verbose_name='Dirección de Residencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_adicional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Información Adicional de Usuario',
                'verbose_name_plural': 'Información Adicional de Usuarios',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
